package com.ftn.sbnz.model.models.enums;

public enum BurningMatter {
    WOOD, PAPER, PLASTICS, RUBBER, OTHER_SOLID_MATERIAL, OTHER_LIQUID_MATERIAL, OTHER_METAL, OTHER_GAS, ELECTRICAL_INSTALLATION, ELECTRONIC_EQUIPMENT, APPLIANCE, BUTANE, METHANE, PROPANE, SODIUM, MAGNESIUM, TITANIUM, METHANOL, ETHANOL, ACETONE, HEXANE, PENTANE, BUTANOL, TOLUENE
}