package com.ftn.sbnz.model.models.enums;

public enum WarningType {
    FIRE_DRIFT_EFFECT, RESCUE_INACTIVE_FIREFIGHTER, LOW_HEARTBEAT_WARN, HIGH_HEARTBEAT_WARN, LOW_HEARTBEAT_EVACUATE, HIGH_HEARTBEAT_EVACUATE, LOW_HEARTBEAT_RESCUE, HIGH_HEARTBEAT_RESCUE, LACK_O2_WARN, LACK_O2_MEDIUM_EVACUATE, LACK_O2_HIGH_RESCUE,
}
