package rules.backward;

import com.ftn.sbnz.model.models.Step
import com.ftn.sbnz.model.models.IncidentReport
import com.ftn.sbnz.model.models.ValidStep
import java.util.List
import java.util.Date


query isValidStepSequence( String currentStep, int index )
    not Step( nextStep, index + 1; )
    or
    ( Step( nextStep, index + 1 ;)
      and ValidStep( currentStep, nextStep; )
      and isValidStepSequence( nextStep, index + 1 ;)
    )
end


rule "Validate Incident Report"
when
    IncidentReport($id: fireId)
    Step($name: name, order == 1)
    isValidStepSequence($name, 1;)
then
    System.out.println("Valid Incident Report with Fire ID: " + $id);
end

rule "Invalid Incident Report"
when
    IncidentReport($id: fireId)
    Step($name: name, order == 1)
    not (isValidStepSequence($name, 1;))
then
    System.out.println("Invalid Incident Report with Fire ID: " + $id);
end